name: Continous Integration

on: [push, pull_request]

jobs:
  test-saucelabs:
    name: Browser tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: npm
      - name: npm install
        run: npm ci
      - name: Build
        run: npm run build
      - name: Run tests
        run: npm run test-saucelabs

  test-node:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 10 # minimum supported version
          - 14 # current LTS
          - 16 # latest
    name: Node.js ${{ matrix.node-version }} test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - name: npm install
        run: npm ci
      - name: Build
        run: npm run build
      - name: Run tests
        run: npm run test-node
